; Generated by TinyC for CPU16
.DATA
ZERO: .WORD 0
sum: .RESW 1
i: .RESW 1

.CODE
.ORG 0x0000
    CALL MAIN
    HLT
main:
    MOV R0, 0
    MOV [DATA + sum], R0
    MOV R0, 10
    MOV [DATA + i], R0
L_0:
    MOV R0, [DATA + i]
    CMP R0, 0
    JZ L_1
    MOV R0, [DATA + sum]
    PUSH R0
    MOV R0, [DATA + i]
    POP R1
    ADD R1, R0
    MOV R0, R1
    MOV [DATA + sum], R0
    MOV R0, [DATA + i]
    PUSH R0
    MOV R0, 1
    POP R1
    SUB R1, R0
    MOV R0, R1
    MOV [DATA + i], R0
    JMP L_0
L_1:
    MOV R0, 0
    RET
    RET
